import Footer from './components/footer.js'
import Navbar from './components/navbar.js'
import loginForm from './components/login/login-form.js'
import registerForm from './components/register/register-form.js'
import userContainer from './components/user/user-container.js'