import Footer from './components/footer.js'
import Navbar from './components/navbar.js'
import loginForm from './components/login/login-form.js'
import registerForm from './components/register/register-form.js'
import userContainer from './components/user/user-container.js'
import profilesContainer from './components/profiles/profiles-container.js'
// import projectsContainer from './components/projects/projects-container.js'
import addProject from './components/profiles/add-project.js'